author: "Bobby Avery"
title: "Bobby Avery"
collections:
  blog:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: []
description: "The personal website of Bobby Avery."
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "projects"
    values:
      feed: /feed.xml
  -
    scope:
      path: ""
      type: "blog"
    values:
      feed: /blog/feed.xml
exclude:
  - bootstrap
optional_front_matter:
  enabled: false
feed:
  collections:
    blog:
      path: /blog/feed.xml
    projects:
      path: /feed.xml
  # we don't actually want this feed, but we
  # have to turn it on for jekyll-feed to run
  path: /all.xml
permalink: /:title/
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
readme_index:
  enabled: false
relative_links:
  collections: true
repository: milkey-mouse/please-admit.me
sass:
  style: compressed
social:
  links:
    - https://github.com/milkey-mouse
    - https://news.ycombinator.com/user?id=milkey_mouse
    - https://hackaday.io/MilkeyMouse
    - https://keybase.io/milkeymouse
    - https://www.thingiverse.com/Milkey_Mouse/designs
google_site_verification: XV-3PEUXIABK5mXgFTp0vUdJZUppWhNy698Vk9CdShs
